"""

Revision ID: 6842299af126
Revises: 6bd72c3ccfae
Create Date: 2025-12-26 17:32:43.898856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6842299af126'
down_revision: Union[str, Sequence[str], None] = '6bd72c3ccfae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'], ondelete='SET NULL')
    op.alter_column('oauth_accounts', 'provider',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('oauth_accounts', 'provider_user_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.create_index('ix_oauth_accounts_provider_user', 'oauth_accounts', ['provider', 'provider_user_id'], unique=False)
    op.create_index('ix_oauth_accounts_user_id', 'oauth_accounts', ['user_id'], unique=False)
    op.drop_column('oauth_accounts', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_accounts', sa.Column('access_token', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_index('ix_oauth_accounts_user_id', table_name='oauth_accounts')
    op.drop_index('ix_oauth_accounts_provider_user', table_name='oauth_accounts')
    op.alter_column('oauth_accounts', 'provider_user_id',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('oauth_accounts', 'provider',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')
    # ### end Alembic commands ###
