"""delete_type_in_tasks

Revision ID: 17648644f0a8
Revises: 2707399fd4cc
Create Date: 2025-10-11 17:25:47.619012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17648644f0a8'
down_revision: Union[str, Sequence[str], None] = '2707399fd4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('type', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
