"""

Revision ID: 8507ba7c5153
Revises: c26e7d689500
Create Date: 2025-10-29 18:03:21.459445

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8507ba7c5153"
down_revision: Union[str, Sequence[str], None] = "c26e7d689500"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "pomodoro_count",
        existing_type=sa.INTEGER(),
        type_=sa.SmallInteger(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "pomodoro_count",
        existing_type=sa.SmallInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
