"""

Revision ID: c60f0841a9a0
Revises: 
Create Date: 2025-11-15 16:25:27.427147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c60f0841a9a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(length=256), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('variant', sa.String(length=50), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("owner_type IN ('user', 'task', 'category')", name='check_owner_type'),
    sa.CheckConstraint("variant IN ('original', 'thumb', 'small')", name='check_variant'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_files_author_id'), 'files', ['author_id'], unique=False)
    op.create_index(op.f('ix_files_owner_type'), 'files', ['owner_type'], unique=False)
    op.drop_index(op.f('ix_images_owner_id'), table_name='images')
    op.drop_index(op.f('ix_images_owner_type'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bucket', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('variant', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mime', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('size', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint("owner_type::text = ANY (ARRAY['user'::character varying, 'task'::character varying, 'category'::character varying]::text[])", name=op.f('check_owner_type')),
    sa.CheckConstraint("variant::text = ANY (ARRAY['original'::character varying, 'thumb'::character varying, 'small'::character varying]::text[])", name=op.f('check_variant')),
    sa.PrimaryKeyConstraint('id', name=op.f('images_pkey')),
    sa.UniqueConstraint('key', name=op.f('images_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_images_owner_type'), 'images', ['owner_type'], unique=False)
    op.create_index(op.f('ix_images_owner_id'), 'images', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_files_owner_type'), table_name='files')
    op.drop_index(op.f('ix_files_author_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
